### ISSUE TITLE
Feature Request / Multiple files

### ISSUE THREAD

**Issue by jeff-skoldberg-gmds** [ak--47/carvis#2]
If you are accepting feature requests, it would be cool to see something like `--max-row-per-file` or `--max-file-size` flag.

That way we can run `npx carvis --json --rows 30000000 --days 90 --max-rows-per-file 1000000` and it would create 30 files.

**Comment by ak--47** [comment]
@jeff-skoldberg-gmds thanks for the note. 

I will consider this as a feature request and leave this open for now.

to unblock your use case; try a  `for in` loop:

```
# generate 10 files, each with 1000 rows
for i in {1..10}; do npx carvis --json --rows 1000 --days 90; done
```


pass the `--silent` flag if you don't want to see the logo each time 😃

**Comment by jeff-skoldberg-gmds** [comment]
thank you kindly, sir!

**Comment by ak--47** [comment]
closing; probably will not implement this API.
